// BLP Resource Library — catalog data
// To add a resource, append an object here. Categories:
//   parts    → Replacement Parts        (BLP-1xx)
//   fixtures → Jigs & Fixtures          (BLP-2xx)
//   player   → Player Piano             (BLP-3xx)
//   cabinet  → Cabinet & Hardware       (BLP-4xx)
//   video    → Training Videos          (BLP-5xx)

const RESOURCES = [
  // ---- Replacement Parts (action, dampers, flanges) ----
  { id: "BLP-101", cat: "parts", title: "Kimball Brass Damper Flange",
    maker: "Kimball", desc: "Reverse-engineered brass damper flange, modeled in Fusion 360 and ready to print or machine.",
    formats: ["F3D"], fusion: "https://a360.co/4f5X9SY", thumb: "thumbs/BLP-101.jpg", by: "brigham-larson", dateAdded: "2026-05-30" },
  { id: "BLP-102", cat: "parts", title: "Chickering 80147 Damper Lever",
    maker: "Chickering", desc: "Damper lever from Chickering serial 80147. Modeled from the original part.",
    formats: ["F3D"], fusion: "https://a360.co/4w0rkks", thumb: "thumbs/BLP-102.jpg", by: "brigham-larson", dateAdded: "2026-06-02" },
  { id: "BLP-103", cat: "parts", title: "Steinway Over-Damper Head",
    maker: "Steinway & Sons", desc: "Over-damper head reconstruction for early Steinway upright actions.",
    formats: ["F3D"], fusion: "https://a360.co/454qvv1", thumb: "thumbs/BLP-103.jpg", by: "brigham-larson", dateAdded: "2026-06-08" },
  { id: "BLP-104", cat: "parts", title: "Steinway Damper Head",
    maker: "Steinway & Sons", desc: "Standard damper head modeled from an original Steinway part.",
    formats: ["F3D"], fusion: "https://a360.co/4ffxiXA", thumb: "thumbs/BLP-104.jpg", by: "brigham-larson", dateAdded: "2026-06-05" },
  { id: "BLP-105", cat: "parts", title: "Knabe Flange — Top Section",
    maker: "Wm. Knabe & Co.", desc: "Top section of a Knabe action flange, split for practical fabrication.",
    formats: ["F3D"], fusion: "https://a360.co/4fhfn2y", thumb: "thumbs/BLP-105.jpg", by: "brigham-larson", dateAdded: "2026-06-22" },
  { id: "BLP-106", cat: "parts", title: "Knabe Double Hammer Flange",
    maker: "Wm. Knabe & Co.", desc: "Double hammer flange for Knabe actions — an obsolete part unavailable from suppliers.",
    formats: ["F3D"], fusion: "https://a360.co/4fn5YGV", thumb: "thumbs/BLP-106.jpg", by: "brigham-larson", dateAdded: "2026-07-14" },
  { id: "BLP-107", cat: "parts", title: "Knabe 116388 Little Comb Piece",
    maker: "Wm. Knabe & Co.", desc: "Small comb piece from Knabe serial 116388. A tiny part that stops a whole restoration when it breaks.",
    formats: ["F3D"], fusion: "https://a360.co/4bN22y7", thumb: "thumbs/BLP-107.jpg", by: "brigham-larson", dateAdded: "2026-06-25" },
  { id: "BLP-108", cat: "parts", title: "Emerson Flange",
    maker: "Emerson Piano Co.", desc: "Standard action flange for Emerson uprights.",
    formats: ["F3D"], fusion: "https://a360.co/3TCwt3L", thumb: "thumbs/BLP-108.jpg", by: "brigham-larson", dateAdded: "2026-06-16" },
  { id: "BLP-109", cat: "parts", title: "Emerson High-Treble Flange",
    maker: "Emerson Piano Co.", desc: "High-treble variant of the Emerson action flange.",
    formats: ["F3D"], fusion: "https://a360.co/4bqq0PA", thumb: "thumbs/BLP-109.jpg", by: "brigham-larson", dateAdded: "2026-06-19" },
  { id: "BLP-110", cat: "parts", title: "K&B 37121 Double Flange",
    maker: "Kohler & Brambach", desc: "Double flange from K&B serial 37121 — primary version.",
    formats: ["F3D"], fusion: "https://a360.co/4wooiHb", thumb: "thumbs/BLP-110.jpg", by: "brigham-larson", dateAdded: "2026-07-06" },
  { id: "BLP-111", cat: "parts", title: "K&B 37121 Double Flange — Variation 2",
    maker: "Kohler & Brambach", desc: "Second modeled variation of the K&B 37121 double flange.",
    formats: ["F3D"], fusion: "https://a360.co/3T2vQ3s", thumb: "thumbs/BLP-111.jpg", by: "brigham-larson", dateAdded: "2026-07-07" },
  { id: "BLP-112", cat: "parts", title: "K&B 37121 Double Flange — Variation 3",
    maker: "Kohler & Brambach", desc: "Third modeled variation of the K&B 37121 double flange.",
    formats: ["F3D"], fusion: "https://a360.co/3SUd9Pt", thumb: "thumbs/BLP-112.jpg", by: "brigham-larson", dateAdded: "2026-07-08" },
  { id: "BLP-113", cat: "parts", title: "K&B 37121 Whippen Flange",
    maker: "Kohler & Brambach", desc: "Whippen flange from the same K&B 37121 action set.",
    formats: ["F3D"], fusion: "https://a360.co/4fEdRZK", thumb: "thumbs/BLP-113.jpg", by: "brigham-larson", dateAdded: "2026-07-09" },

  // ---- Jigs & Fixtures ----
  { id: "BLP-201", cat: "fixtures", title: "Initial Key Height Setter",
    maker: "BLP Shop Fixture", desc: "Shop-built fixture for setting initial key height quickly and consistently across the keyboard.",
    formats: ["F3D"], fusion: "https://a360.co/4be1ot8", thumb: "thumbs/BLP-201.jpg", by: "brigham-larson", dateAdded: "2026-07-13" },
  { id: "BLP-202", cat: "fixtures", title: "Grand Hammer Coving Jig",
    maker: "BLP Shop Fixture", desc: "Jig for coving grand hammers — pairs with the coving training video below.",
    formats: ["F3D"], fusion: "https://a360.co/4vBJfO8", thumb: "thumbs/BLP-202.jpg", by: "brigham-larson", dateAdded: "2026-06-28" },

  // ---- Player Piano ----
  { id: "BLP-301", cat: "player", title: "Emerson Player Deck",
    maker: "Emerson Piano Co.", desc: "Player deck reconstruction for Emerson player uprights.",
    formats: ["F3D"], fusion: "https://a360.co/3RlRv5Y", thumb: "thumbs/BLP-301.jpg", by: "brigham-larson", dateAdded: "2026-07-01" },
  { id: "BLP-302", cat: "player", title: "Gulbransen 149314 Player Elbow",
    maker: "Gulbransen", desc: "Player action elbow from Gulbransen serial 149314 — a classic crumble-prone part, now printable.",
    formats: ["F3D"], fusion: "https://a360.co/4w5CCnt", thumb: "thumbs/BLP-302.jpg", by: "brigham-larson", dateAdded: "2026-07-12" },

  // ---- Cabinet & Hardware ----
  { id: "BLP-401", cat: "cabinet", title: "Bush & Lane Column — 75% Scale Solid",
    maker: "Bush & Lane", desc: "Decorative cabinet column modeled as a solid at 75% scale for CNC reproduction.",
    formats: ["F3D"], fusion: "https://a360.co/4xYF2py", thumb: "thumbs/BLP-401.jpg", by: "brigham-larson", dateAdded: "2026-07-11" },
  { id: "BLP-402", cat: "cabinet", title: "Steinway Small Lid Prop",
    maker: "Steinway & Sons", desc: "Small lid prop stick, modeled for replacement when originals go missing.",
    formats: ["F3D"], fusion: "https://a360.co/4bECy5V", thumb: "thumbs/BLP-402.jpg", by: "brigham-larson", dateAdded: "2026-06-12" },
  { id: "BLP-403", cat: "cabinet", title: "Wurlitzer 983993 Music Desk",
    maker: "Wurlitzer", desc: "Complete music desk from Wurlitzer serial 983993, modeled for fretwork reproduction.",
    formats: ["F3D"], fusion: "https://a360.co/4ypmkHO", thumb: "thumbs/BLP-403.jpg", by: "brigham-larson", dateAdded: "2026-07-04" },
  { id: "BLP-404", cat: "cabinet", title: "Music Desk — 'Ken in WA' Project",
    maker: "Client Restoration", desc: "Custom music desk reconstruction from a client restoration project in Washington.",
    formats: ["F3D"], fusion: "https://a360.co/4oQd0bs", thumb: "thumbs/BLP-404.jpg", by: "brigham-larson", dateAdded: "2026-07-03" },

  // ---- Training Videos (scraped from the BLP YouTube channel) ----
// 100 training videos scraped from the Brigham Larson Pianos YouTube channel
  { id: "BLP-V001", cat: "video", sub: "grand-reg", title: "Regulating Jack Position on a Grand",
    dur: "16:20", youtube: "zM_gg2WRZN0", by: "brigham-larson", dateAdded: "2026-06-30" },
  { id: "BLP-V002", cat: "video", sub: "grand-reg", title: "Finalizing After Touch",
    dur: "18:23", youtube: "7l9umCB8MLQ", by: "brigham-larson", dateAdded: "2026-06-29" },
  { id: "BLP-V003", cat: "video", sub: "grand-reg", title: "Grand Back check alignment",
    dur: "14:54", youtube: "kjR6pTae8cE", by: "brigham-larson", dateAdded: "2026-06-27" },
  { id: "BLP-V004", cat: "video", sub: "grand-reg", title: "Before Starting Grand Regulation: Spring Strength, Drop, & Dip",
    dur: "14:00", youtube: "GJgrz7dp3Is", by: "brigham-larson", dateAdded: "2026-06-25" },
  { id: "BLP-V005", cat: "video", sub: "grand-reg", title: "Grand Piano Regulation Theory (Unedited)",
    dur: "35:08", youtube: "MiTS2FiAa3I", by: "brigham-larson", dateAdded: "2026-06-23" },
  { id: "BLP-V006", cat: "video", sub: "grand-reg", title: "How to do Accurate and FAST Grand Piano Let-Off",
    dur: "6:40", youtube: "8Yjft-yIjGE", by: "brigham-larson", dateAdded: "2026-06-21" },
  { id: "BLP-V007", cat: "video", sub: "grand-reg", title: "Grand Piano Regulation Theory",
    dur: "15:22", youtube: "ff37ciHxhkc", by: "brigham-larson", dateAdded: "2026-06-20" },
  { id: "BLP-V008", cat: "video", sub: "grand-reg", title: "Tricks for Let Off Regulation",
    dur: "4:18", youtube: "2Ww35DGd2bw", by: "brigham-larson", dateAdded: "2026-06-18" },
  { id: "BLP-V009", cat: "video", sub: "grand-reg", title: "Aligning Backchecks",
    dur: "10:21", youtube: "RYrvzx4f8t4", by: "brigham-larson", dateAdded: "2026-06-16" },
  { id: "BLP-V010", cat: "video", sub: "upright-reg", title: "Most Common Upright Pedal Squeaks Coming from the Action",
    dur: "11:00", youtube: "5j0AL4sGef8", by: "brigham-larson", dateAdded: "2026-06-14" },
  { id: "BLP-V011", cat: "video", sub: "upright-reg", title: "Improving Piano Touch with Upright Regulation-Aligning backchecks to catchers",
    dur: "3:26", youtube: "hc8si1K7oJA", by: "brigham-larson", dateAdded: "2026-06-12" },
  { id: "BLP-V012", cat: "video", sub: "upright-reg", title: "Upright Piano Regulation Theory",
    dur: "13:08", youtube: "uou0M_W9OJw", by: "brigham-larson", dateAdded: "2026-06-11" },
  { id: "BLP-V013", cat: "video", sub: "upright-reg", title: "Choosing Rest Rail Height",
    dur: "16:38", youtube: "F6QyuY9HaRo", by: "brigham-larson", dateAdded: "2026-06-09" },
  { id: "BLP-V014", cat: "video", sub: "upright-reg", title: "Tricks for Lost Motion Regulating",
    dur: "5:49", youtube: "KfxKyqUrl8k", by: "brigham-larson", dateAdded: "2026-06-07" },
  { id: "BLP-V015", cat: "video", sub: "hammers", title: "Arcing Grand Hammers",
    dur: "22:07", youtube: "hj_bIK1H3hU", by: "brigham-larson", dateAdded: "2026-06-05" },
  { id: "BLP-V016", cat: "video", sub: "hammers", title: "Tapering Bass Hammers",
    dur: "23:05", youtube: "SU8YD6uUtNk", by: "brigham-larson", dateAdded: "2026-06-03" },
  { id: "BLP-V017", cat: "video", sub: "hammers", title: "Grand Piano Hammers: Choosing the Optimal Strike Point",
    dur: "26:37", youtube: "xTJygqgcH7M", by: "brigham-larson", dateAdded: "2026-06-02" },
  { id: "BLP-V018", cat: "video", sub: "hammers", title: "Prevoicing Piano Hammers",
    dur: "9:00", youtube: "qOY1YZ-xALQ", by: "brigham-larson", dateAdded: "2026-05-31" },
  { id: "BLP-V019", cat: "video", sub: "hammers", title: "Grand Hammer Alignment",
    dur: "10:11", youtube: "d-BJ1XGkySQ", by: "brigham-larson", dateAdded: "2026-05-29" },
  { id: "BLP-V020", cat: "video", sub: "hammers", title: "Upright Hammer Hanging Part 2",
    dur: "16:27", youtube: "t4Royxifoe8", by: "brigham-larson", dateAdded: "2026-05-27" },
  { id: "BLP-V021", cat: "video", sub: "hammers", title: "Upright Hammer Alignment",
    dur: "7:41", youtube: "dpCf_ATfxDM", by: "brigham-larson", dateAdded: "2026-05-25" },
  { id: "BLP-V022", cat: "video", sub: "hammers", title: "Needle Voicing Piano Hammers for Improved Tone",
    dur: "21:54", youtube: "WUl0OPbvPqA", by: "brigham-larson", dateAdded: "2026-05-24" },
  { id: "BLP-V023", cat: "video", sub: "hammers", title: "Voicing Piano Hammers with Steam for Improved Tone",
    dur: "9:47", youtube: "15TFBQJYWvM", by: "brigham-larson", dateAdded: "2026-05-22" },
  { id: "BLP-V024", cat: "video", sub: "hammers", title: "Upright Hammer Hanging Part 1",
    dur: "13:00", youtube: "SRo9_MojyDs", by: "brigham-larson", dateAdded: "2026-05-20" },
  { id: "BLP-V025", cat: "video", sub: "hammers", title: "Planning Upright Hammer Boring",
    dur: "13:51", youtube: "vkibGtKz9vA", by: "brigham-larson", dateAdded: "2026-05-18" },
  { id: "BLP-V026", cat: "video", sub: "hammers", title: "Hanging Grand Piano Hammers",
    dur: "17:25", youtube: "5NQn6sXNQBo", by: "brigham-larson", dateAdded: "2026-05-16" },
  { id: "BLP-V027", cat: "video", sub: "hammers", title: "Choosing Hammer Strike Point",
    dur: "13:55", youtube: "rTBrlh5-Yes", by: "brigham-larson", dateAdded: "2026-05-15" },
  { id: "BLP-V028", cat: "video", sub: "hammers", title: "Coving Grand Hammers",
    dur: "6:14", youtube: "76hzLDsLd4o", by: "brigham-larson", dateAdded: "2026-05-13" },
  { id: "BLP-V029", cat: "video", sub: "hammers", title: "Upright Hammer Reshaping",
    dur: "13:20", youtube: "-eKvSEGGsZo", by: "brigham-larson", dateAdded: "2026-05-11" },
  { id: "BLP-V030", cat: "video", sub: "hammers", title: "Grand Hammer Prep",
    dur: "22:46", youtube: "W9xUNY9A4Gw", by: "brigham-larson", dateAdded: "2026-05-09" },
  { id: "BLP-V031", cat: "video", sub: "dampers", title: "Installing Trichord Dampers",
    dur: "24:22", youtube: "6J9d3tRwg5k", by: "brigham-larson", dateAdded: "2026-05-07" },
  { id: "BLP-V032", cat: "video", sub: "dampers", title: "Upright Damper Head Alignment",
    dur: "17:50", youtube: "5EZnh0_hm3Y", by: "brigham-larson", dateAdded: "2026-05-06" },
  { id: "BLP-V033", cat: "video", sub: "dampers", title: "Upright Trichord Damper Ironing",
    dur: "7:30", youtube: "guPVfie8a2I", by: "brigham-larson", dateAdded: "2026-05-04" },
  { id: "BLP-V034", cat: "video", sub: "dampers", title: "Damper Spoon Regulation",
    dur: "9:57", youtube: "eTvxjx1yy2E", by: "brigham-larson", dateAdded: "2026-05-02" },
  { id: "BLP-V035", cat: "video", sub: "dampers", title: "Damper Lift",
    dur: "11:30", youtube: "9xAn4u6RzlA", by: "brigham-larson", dateAdded: "2026-04-30" },
  { id: "BLP-V036", cat: "video", sub: "keys", title: "How To Fix A Warped Piano Key",
    dur: "9:01", youtube: "NYf1pea4lMU", by: "brigham-larson", dateAdded: "2026-04-28" },
  { id: "BLP-V037", cat: "video", sub: "keys", title: "Piano Repair: Broken key stick repair",
    dur: "5:33", youtube: "pZhKxu_n1-4", by: "brigham-larson", dateAdded: "2026-04-27" },
  { id: "BLP-V038", cat: "video", sub: "keys", title: "Sanding the Tops of Sharps Together",
    dur: "4:00", youtube: "W-9FlcU9cYA", by: "brigham-larson", dateAdded: "2026-04-25" },
  { id: "BLP-V039", cat: "video", sub: "keys", title: "How to Repair a Broken Keytop",
    dur: "9:32", youtube: "nQThNrHSfGE", by: "brigham-larson", dateAdded: "2026-04-23" },
  { id: "BLP-V040", cat: "video", sub: "keys", title: "How to Apply Ivory to a Key",
    dur: "7:36", youtube: "Fs4eREUxh-0", by: "brigham-larson", dateAdded: "2026-04-21" },
  { id: "BLP-V041", cat: "video", sub: "keys", title: "Key Leveling",
    dur: "6:15", youtube: "qIKca27rVQ0", by: "brigham-larson", dateAdded: "2026-04-19" },
  { id: "BLP-V042", cat: "video", sub: "keys", title: "In The Shop: All About Piano Keys 🎹",
    dur: "4:46", youtube: "S8kgbB0ZbfQ", by: "brigham-larson", dateAdded: "2026-04-18" },
  { id: "BLP-V043", cat: "video", sub: "keys", title: "Piano Keytop Restoration Step 1: Recovering piano keytops using a numbering machine",
    dur: "6:12", youtube: "kX6A1eqHV9M", by: "brigham-larson", dateAdded: "2026-04-16" },
  { id: "BLP-V044", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 2 -  removing the old key top",
    dur: "9:58", youtube: "EXY52IuNOq4", by: "brigham-larson", dateAdded: "2026-04-14" },
  { id: "BLP-V045", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 3 - Removing the Key front",
    dur: "8:38", youtube: "IAYENxkVzH8", by: "brigham-larson", dateAdded: "2026-04-12" },
  { id: "BLP-V046", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 4 - Gluing on the New Keytop",
    dur: "7:33", youtube: "XkMMdEFfJec", by: "brigham-larson", dateAdded: "2026-04-10" },
  { id: "BLP-V047", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 5 - Rough Trimming",
    dur: "6:14", youtube: "h3AE-G7Sdqs", by: "brigham-larson", dateAdded: "2026-04-09" },
  { id: "BLP-V048", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 6 - Notching",
    dur: "11:53", youtube: "vM3p_yVFPyM", by: "brigham-larson", dateAdded: "2026-04-07" },
  { id: "BLP-V049", cat: "video", sub: "keys", title: "Piano Keytop Restoration: Step 7 - (Last Step) Hand Filing",
    dur: "17:50", youtube: "Fp7Mas0M1vI", by: "brigham-larson", dateAdded: "2026-04-05" },
  { id: "BLP-V050", cat: "video", sub: "keys", title: "How to Remove Ivory Keytops",
    dur: "1:24", youtube: "3tcufoCoPg0", by: "brigham-larson", dateAdded: "2026-04-03" },
  { id: "BLP-V051", cat: "video", sub: "keys", title: "How to Remove Piano Key Tops",
    dur: "3:53", youtube: "39x_YSWrqEQ", by: "brigham-larson", dateAdded: "2026-04-01" },
  { id: "BLP-V052", cat: "video", sub: "action", title: "Piano Technician Grand Repair - \"How to Repair a Broken Flange Birdseye\"",
    dur: "11:59", youtube: "o5kt4vHYiuM", by: "brigham-larson", dateAdded: "2026-03-31" },
  { id: "BLP-V053", cat: "video", sub: "action", title: "Part 1: Fixing a Broken Shank",
    dur: "5:05", youtube: "cT6PhpF1TDQ", by: "brigham-larson", dateAdded: "2026-03-29" },
  { id: "BLP-V054", cat: "video", sub: "action", title: "Part 2: Fixing a Broken Shank",
    dur: "13:22", youtube: "v3WjOrAgcZM", by: "brigham-larson", dateAdded: "2026-03-27" },
  { id: "BLP-V055", cat: "video", sub: "action", title: "Grand Piano Restoration Step:Pre-Regulation by Replacing Old Whippen Strings (only sometimes needed)",
    dur: "8:39", youtube: "TRT7DIy_OZc", by: "brigham-larson", dateAdded: "2026-03-25" },
  { id: "BLP-V056", cat: "video", sub: "action", title: "Installing New Elbows",
    dur: "5:37", youtube: "-RwL9h_gnKw", by: "brigham-larson", dateAdded: "2026-03-23" },
  { id: "BLP-V057", cat: "video", sub: "action", title: "Flange Rebushing",
    dur: "5:30", youtube: "nU34eWP46t4", by: "brigham-larson", dateAdded: "2026-03-22" },
  { id: "BLP-V058", cat: "video", sub: "action", title: "Sizing Flange Bushing Cloth",
    dur: "5:58", youtube: "1ZuUpmgVmvQ", by: "brigham-larson", dateAdded: "2026-03-20" },
  { id: "BLP-V059", cat: "video", sub: "action", title: "How to Replace an Upright Hammer Shank",
    dur: "10:20", youtube: "rCccCSTa01E", by: "brigham-larson", dateAdded: "2026-03-18" },
  { id: "BLP-V060", cat: "video", sub: "action", title: "Flange Rebushing",
    dur: "9:48", youtube: "TiOZDBqyoek", by: "brigham-larson", dateAdded: "2026-03-16" },
  { id: "BLP-V061", cat: "video", sub: "strings", title: "How to Raise the Pitch of a Piano",
    dur: "1:08:59", youtube: "YSSEIiP4biY", by: "brigham-larson", dateAdded: "2026-03-14" },
  { id: "BLP-V062", cat: "video", sub: "strings", title: "How to Replace a String",
    dur: "40:56", youtube: "ioppmSDCCfs", by: "brigham-larson", dateAdded: "2026-03-13" },
  { id: "BLP-V063", cat: "video", sub: "strings", title: "Measuring Bass Strings",
    dur: "17:52", youtube: "8NVCCZhnm6g", by: "brigham-larson", dateAdded: "2026-03-11" },
  { id: "BLP-V064", cat: "video", sub: "strings", title: "Restringing an Upright Piano",
    dur: "34:50", youtube: "ZFKaFvEcz_w", by: "brigham-larson", dateAdded: "2026-03-09" },
  { id: "BLP-V065", cat: "video", sub: "strings", title: "How to Tie a Bass String",
    dur: "18:39", youtube: "HQPjweWFgaU", by: "brigham-larson", dateAdded: "2026-03-07" },
  { id: "BLP-V066", cat: "video", sub: "strings", title: "Tuning won’t hold?? Never fail loose pin treatment…",
    dur: "7:51", youtube: "mfYOkE46jb8", by: "brigham-larson", dateAdded: "2026-03-05" },
  { id: "BLP-V067", cat: "video", sub: "strings", title: "Removing Bass Strings",
    dur: "4:58", youtube: "yDbebV6poUU", by: "brigham-larson", dateAdded: "2026-03-04" },
  { id: "BLP-V068", cat: "video", sub: "strings", title: "Removing Tuning Pins",
    dur: "3:21", youtube: "Lx3rYFHvnVE", by: "brigham-larson", dateAdded: "2026-03-02" },
  { id: "BLP-V069", cat: "video", sub: "strings", title: "Measuring Piano Strings",
    dur: "10:30", youtube: "p8pdISpvWCo", by: "brigham-larson", dateAdded: "2026-02-28" },
  { id: "BLP-V070", cat: "video", sub: "bridges", title: "Filling Bridge Root Holes with Shoe Pegs",
    dur: "2:47", youtube: "b8cdxrAh3x0", by: "brigham-larson", dateAdded: "2026-02-26" },
  { id: "BLP-V071", cat: "video", sub: "bridges", title: "Cutting off the old Bridge Cap",
    dur: "4:29", youtube: "PxWwCj8upGU", by: "brigham-larson", dateAdded: "2026-02-24" },
  { id: "BLP-V072", cat: "video", sub: "bridges", title: "Gluing Brand New Steinway Sound Board",
    dur: "5:06", youtube: "adar7wIOvzI", by: "brigham-larson", dateAdded: "2026-02-23" },
  { id: "BLP-V073", cat: "video", sub: "bridges", title: "Making a Mylar Bridge Pattern",
    dur: "14:16", youtube: "Yygt9ntexa4", by: "brigham-larson", dateAdded: "2026-02-21" },
  { id: "BLP-V074", cat: "video", sub: "bridges", title: "Gluing a Cracked Bass Apron",
    dur: "6:17", youtube: "jY0RjJRoi6w", by: "brigham-larson", dateAdded: "2026-02-19" },
  { id: "BLP-V075", cat: "video", sub: "bridges", title: "Removing Bass Bridge Pins",
    dur: "4:34", youtube: "zhydBfCnWdk", by: "brigham-larson", dateAdded: "2026-02-17" },
  { id: "BLP-V076", cat: "video", sub: "bridges", title: "Removing an Upright Bass Bridge",
    dur: "10:01", youtube: "D4nldy6U1VM", by: "brigham-larson", dateAdded: "2026-02-15" },
  { id: "BLP-V077", cat: "video", sub: "bridges", title: "Repair of Separated Ribs",
    dur: "17:22", youtube: "Qv-UZOqh0og", by: "brigham-larson", dateAdded: "2026-02-14" },
  { id: "BLP-V078", cat: "video", sub: "bridges", title: "Sanding the Bass Apron",
    dur: "5:34", youtube: "qyaqQAEYmDI", by: "brigham-larson", dateAdded: "2026-02-12" },
  { id: "BLP-V079", cat: "video", sub: "bridges", title: "Cutting out a New Bass Bridge Cap",
    dur: "4:09", youtube: "M_k3B-n5oT4", by: "brigham-larson", dateAdded: "2026-02-10" },
  { id: "BLP-V080", cat: "video", sub: "bridges", title: "Gluing New Bridge Cap to Old Bridge Root",
    dur: "3:49", youtube: "qkG7q2RLzCI", by: "brigham-larson", dateAdded: "2026-02-08" },
  { id: "BLP-V081", cat: "video", sub: "bridges", title: "How to Trim the Bridgecap Flush with the Bridge Root",
    dur: "7:58", youtube: "vyxERgBBmxQ", by: "brigham-larson", dateAdded: "2026-02-06" },
  { id: "BLP-V082", cat: "video", sub: "bridges", title: "Determining Piano Bridge Height for New Upright Bridge Cap",
    dur: "4:56", youtube: "T-O-mZfDuTg", by: "brigham-larson", dateAdded: "2026-02-05" },
  { id: "BLP-V083", cat: "video", sub: "bridges", title: "Filling Soundboard Rib Screws",
    dur: "4:39", youtube: "t0o5pGkMypI", by: "brigham-larson", dateAdded: "2026-02-03" },
  { id: "BLP-V084", cat: "video", sub: "bridges", title: "Trimming Bridge Cap to New Height",
    dur: "4:05", youtube: "6I7a6opgJQk", by: "brigham-larson", dateAdded: "2026-02-01" },
  { id: "BLP-V085", cat: "video", sub: "bridges", title: "Downbearing",
    dur: "7:14", youtube: "vrpXvvaX_78", by: "brigham-larson", dateAdded: "2026-01-30" },
  { id: "BLP-V086", cat: "video", sub: "shop", title: "Upright Refurbishing Initial Evaluation",
    dur: "30:18", youtube: "dWBZHsV9-qs", by: "brigham-larson", dateAdded: "2026-01-28" },
  { id: "BLP-V087", cat: "video", sub: "shop", title: "Buffing Basics",
    dur: "6:18", youtube: "rGrK3P8fWG0", by: "brigham-larson", dateAdded: "2026-01-27" },
  { id: "BLP-V088", cat: "video", sub: "shop", title: "How to Use Calipers",
    dur: "5:03", youtube: "-SCvqifkwwA", by: "brigham-larson", dateAdded: "2026-01-25" },
  { id: "BLP-V089", cat: "video", sub: "shop", title: "BLP Shop training: Bolt Restoration",
    dur: "3:57", youtube: "qdNi8zIkl3c", by: "brigham-larson", dateAdded: "2026-01-23" },
  { id: "BLP-V090", cat: "video", sub: "shop", title: "The Secret to Buffing the Inside of a Brass Piano Caster",
    dur: "3:54", youtube: "irvCMOP0f8U", by: "brigham-larson", dateAdded: "2026-01-21" },
  { id: "BLP-V091", cat: "video", sub: "shop", title: "How to Sharpen a Chisel",
    dur: "7:33", youtube: "Qx8SBTj-fB0", by: "brigham-larson", dateAdded: "2026-01-19" },
  { id: "BLP-V092", cat: "video", sub: "shop", title: "2 Tricks to Address Tight Bolts and Screws",
    dur: "3:07", youtube: "lCzhvy6TP7U", by: "brigham-larson", dateAdded: "2026-01-18" },
  { id: "BLP-V093", cat: "video", sub: "shop", title: "Routing Upright Caster Recesses",
    dur: "16:10", youtube: "LWccRMzuSlk", by: "brigham-larson", dateAdded: "2026-01-16" },
  { id: "BLP-V094", cat: "video", sub: "shop", title: "Buffing Casters",
    dur: "3:50", youtube: "i_W6HjhNoKI", by: "brigham-larson", dateAdded: "2026-01-14" },
  { id: "BLP-V095", cat: "video", sub: "cnc", title: "How 3D Printing is Revolutionizing Piano Restoration | Piano Technicians Guild Presentation",
    dur: "5:22", youtube: "lSm1mjw6U0g", by: "brigham-larson", dateAdded: "2026-01-12" },
  { id: "BLP-V096", cat: "video", sub: "cnc", title: "How 3D Printing is Revolutionizing Piano Restoration | Piano Technicians Guild FULL Presentation",
    dur: "37:44", youtube: "w_2YOZAxwRE", by: "brigham-larson", dateAdded: "2026-01-10" },
  { id: "BLP-V097", cat: "video", sub: "cnc", title: "CNC Machine Precision Pinblock Restoration Part 1—1909 Friedrich Prein Heirloom Upright",
    dur: "7:42", youtube: "smCUmLe7SCQ", by: "brigham-larson", dateAdded: "2026-01-09" },
  { id: "BLP-V098", cat: "video", sub: "cnc", title: "CNC Machine Precision Pinblock Restoration Part 2—1909 Friedrich Prein Heirloom Upright",
    dur: "11:36", youtube: "ZhmM8XUJ2og", by: "brigham-larson", dateAdded: "2026-01-07" },
  { id: "BLP-V099", cat: "video", sub: "cnc", title: "3D Printing Piano Parts—Elbows",
    dur: "6:52", youtube: "0nAZOWjS8vs", by: "brigham-larson", dateAdded: "2026-01-05" },
  { id: "BLP-V100", cat: "video", sub: "cnc", title: "New CNC Machine—Keytop Jig!",
    dur: "2:15", youtube: "hwtRsq5ULKQ", by: "brigham-larson", dateAdded: "2026-01-03" },
];

const CATEGORIES = [
  { key: "all",      label: "ALL FILES" },
  { key: "parts",    label: "PARTS" },
  { key: "fixtures", label: "JIGS & FIXTURES" },
  { key: "player",   label: "PLAYER PIANO" },
  { key: "cabinet",  label: "CABINET" },
  { key: "video",    label: "VIDEO" },
];

// Sub-topics for the training video collection
const TOPICS = [
  { key: "all",         label: "ALL TOPICS" },
  { key: "grand-reg",   label: "GRAND REGULATION" },
  { key: "upright-reg", label: "UPRIGHT REGULATION" },
  { key: "hammers",     label: "HAMMERS & VOICING" },
  { key: "dampers",     label: "DAMPERS" },
  { key: "keys",        label: "KEYS & KEYTOPS" },
  { key: "action",      label: "ACTION REPAIRS" },
  { key: "strings",     label: "STRINGS & TUNING" },
  { key: "bridges",     label: "BRIDGES & SOUNDBOARD" },
  { key: "shop",        label: "SHOP SKILLS" },
  { key: "cnc",         label: "CNC & 3D PRINTING" },
];

// Contributor registry — every shared resource credits its technician.
// To add a contributor: add an entry here, then reference their key
// in a resource's `by` field.
const CONTRIBUTORS = {
  "brigham-larson": {
    name: "Brigham Larson",
    credential: "RPT — Registered Piano Technician",
    location: "Utah, USA",
    since: "Tuning, fixing and resurrecting pianos since 1995 · RPT since 2003",
    photo: "https://yt3.googleusercontent.com/ytc/AIdro_mo7kWayVyfmrkSbmAqkBNGcClgH4YEHSCR5vZqX-lv1cA=s900-c-k-c0x00ffffff-no-rj",
    bio: "Brigham has been tuning, fixing and resurrecting pianos since 1995 and has been a Registered Piano Technician since 2003. His shop, Brigham Larson Pianos in Utah, restores heirloom pianos and pioneers digital manufacturing for the trade — reverse-engineering obsolete parts in Fusion 360 and producing them with CNC machining and 3D printing. He founded this library so no technician ever has to solve the same specialized problem twice.",
    website: "https://www.brighamlarsonpianos.com",
    links: [
      { label: "WEBSITE",   url: "https://www.brighamlarsonpianos.com" },
      { label: "YOUTUBE",   url: "https://www.youtube.com/@brighamspianoservice" },
      { label: "FACEBOOK",  url: "https://www.facebook.com/BrighamLarsonPianos/" },
      { label: "INSTAGRAM", url: "https://www.instagram.com/brighamlarsonpianos" },
      { label: "TIKTOK",    url: "https://www.tiktok.com/@brighamlarsonpianos" },
      { label: "X",         url: "https://x.com/BrighamsPianos" },
    ],
  },
};
