// BLP Resource Library — catalog data
// To add a resource, append an object here. Categories:
//   parts    → Replacement Parts        (BLP-1xx)
//   fixtures → Jigs & Fixtures          (BLP-2xx)
//   player   → Player Piano             (BLP-3xx)
//   cabinet  → Cabinet & Hardware       (BLP-4xx)
//   video    → Training Videos          (BLP-5xx)

const RESOURCES = [
  // ---- Replacement Parts (action, dampers, flanges) ----
  { id: "BLP-101", cat: "parts", title: "Kimball Brass Damper Flange",
    maker: "Kimball", desc: "Reverse-engineered brass damper flange, modeled in Fusion 360 and ready to print or machine.",
    formats: ["F3D"], fusion: "https://a360.co/4f5X9SY" },
  { id: "BLP-102", cat: "parts", title: "Chickering 80147 Damper Lever",
    maker: "Chickering", desc: "Damper lever from Chickering serial 80147. Modeled from the original part.",
    formats: ["F3D"], fusion: "https://a360.co/4w0rkks" },
  { id: "BLP-103", cat: "parts", title: "Steinway Over-Damper Head",
    maker: "Steinway & Sons", desc: "Over-damper head reconstruction for early Steinway upright actions.",
    formats: ["F3D"], fusion: "https://a360.co/454qvv1" },
  { id: "BLP-104", cat: "parts", title: "Steinway Damper Head",
    maker: "Steinway & Sons", desc: "Standard damper head modeled from an original Steinway part.",
    formats: ["F3D"], fusion: "https://a360.co/4ffxiXA" },
  { id: "BLP-105", cat: "parts", title: "Knabe Flange — Top Section",
    maker: "Wm. Knabe & Co.", desc: "Top section of a Knabe action flange, split for practical fabrication.",
    formats: ["F3D"], fusion: "https://a360.co/4fhfn2y" },
  { id: "BLP-106", cat: "parts", title: "Knabe Double Hammer Flange",
    maker: "Wm. Knabe & Co.", desc: "Double hammer flange for Knabe actions — an obsolete part unavailable from suppliers.",
    formats: ["F3D"], fusion: "https://a360.co/4fn5YGV" },
  { id: "BLP-107", cat: "parts", title: "Knabe 116388 Little Comb Piece",
    maker: "Wm. Knabe & Co.", desc: "Small comb piece from Knabe serial 116388. A tiny part that stops a whole restoration when it breaks.",
    formats: ["F3D"], fusion: "https://a360.co/4bN22y7" },
  { id: "BLP-108", cat: "parts", title: "Emerson Flange",
    maker: "Emerson Piano Co.", desc: "Standard action flange for Emerson uprights.",
    formats: ["F3D"], fusion: "https://a360.co/3TCwt3L" },
  { id: "BLP-109", cat: "parts", title: "Emerson High-Treble Flange",
    maker: "Emerson Piano Co.", desc: "High-treble variant of the Emerson action flange.",
    formats: ["F3D"], fusion: "https://a360.co/4bqq0PA" },
  { id: "BLP-110", cat: "parts", title: "K&B 37121 Double Flange",
    maker: "Kohler & Brambach", desc: "Double flange from K&B serial 37121 — primary version.",
    formats: ["F3D"], fusion: "https://a360.co/4wooiHb" },
  { id: "BLP-111", cat: "parts", title: "K&B 37121 Double Flange — Variation 2",
    maker: "Kohler & Brambach", desc: "Second modeled variation of the K&B 37121 double flange.",
    formats: ["F3D"], fusion: "https://a360.co/3T2vQ3s" },
  { id: "BLP-112", cat: "parts", title: "K&B 37121 Double Flange — Variation 3",
    maker: "Kohler & Brambach", desc: "Third modeled variation of the K&B 37121 double flange.",
    formats: ["F3D"], fusion: "https://a360.co/3SUd9Pt" },
  { id: "BLP-113", cat: "parts", title: "K&B 37121 Whippen Flange",
    maker: "Kohler & Brambach", desc: "Whippen flange from the same K&B 37121 action set.",
    formats: ["F3D"], fusion: "https://a360.co/4fEdRZK" },

  // ---- Jigs & Fixtures ----
  { id: "BLP-201", cat: "fixtures", title: "Initial Key Height Setter",
    maker: "BLP Shop Fixture", desc: "Shop-built fixture for setting initial key height quickly and consistently across the keyboard.",
    formats: ["F3D"], fusion: "https://a360.co/4be1ot8" },
  { id: "BLP-202", cat: "fixtures", title: "Grand Hammer Coving Jig",
    maker: "BLP Shop Fixture", desc: "Jig for coving grand hammers — pairs with the coving training video below.",
    formats: ["F3D"], fusion: "https://a360.co/4vBJfO8" },

  // ---- Player Piano ----
  { id: "BLP-301", cat: "player", title: "Emerson Player Deck",
    maker: "Emerson Piano Co.", desc: "Player deck reconstruction for Emerson player uprights.",
    formats: ["F3D"], fusion: "https://a360.co/3RlRv5Y" },
  { id: "BLP-302", cat: "player", title: "Gulbransen 149314 Player Elbow",
    maker: "Gulbransen", desc: "Player action elbow from Gulbransen serial 149314 — a classic crumble-prone part, now printable.",
    formats: ["F3D"], fusion: "https://a360.co/4w5CCnt" },

  // ---- Cabinet & Hardware ----
  { id: "BLP-401", cat: "cabinet", title: "Bush & Lane Column — 75% Scale Solid",
    maker: "Bush & Lane", desc: "Decorative cabinet column modeled as a solid at 75% scale for CNC reproduction.",
    formats: ["F3D"], fusion: "https://a360.co/4xYF2py" },
  { id: "BLP-402", cat: "cabinet", title: "Steinway Small Lid Prop",
    maker: "Steinway & Sons", desc: "Small lid prop stick, modeled for replacement when originals go missing.",
    formats: ["F3D"], fusion: "https://a360.co/4bECy5V" },
  { id: "BLP-403", cat: "cabinet", title: "Wurlitzer 983993 Music Desk",
    maker: "Wurlitzer", desc: "Complete music desk from Wurlitzer serial 983993, modeled for fretwork reproduction.",
    formats: ["F3D"], fusion: "https://a360.co/4ypmkHO" },
  { id: "BLP-404", cat: "cabinet", title: "Music Desk — 'Ken in WA' Project",
    maker: "Client Restoration", desc: "Custom music desk reconstruction from a client restoration project in Washington.",
    formats: ["F3D"], fusion: "https://a360.co/4oQd0bs" },

  // ---- Training Videos ----
  { id: "BLP-501", cat: "video", title: "Upright Hammer Reshaping",
    maker: "BLP Shop Training", desc: "Reshaping worn upright hammers to restore tone and geometry.",
    formats: ["VIDEO"], youtube: "-eKvSEGGsZo" },
  { id: "BLP-502", cat: "video", title: "Tricks for Let-Off Regulation",
    maker: "BLP Shop Training", desc: "Practical shop tricks for fast, accurate let-off regulation.",
    formats: ["VIDEO"], youtube: "2Ww35DGd2bw" },
  { id: "BLP-503", cat: "video", title: "Upright Damper Head Alignment",
    maker: "BLP Shop Training", desc: "Aligning upright damper heads for clean, even damping.",
    formats: ["VIDEO"], youtube: "5EZnh0_hm3Y" },
  { id: "BLP-504", cat: "video", title: "Coving Grand Hammers",
    maker: "BLP Shop Training", desc: "Coving grand hammers in the shop — pairs with the coving jig (BLP-202).",
    formats: ["VIDEO"], youtube: "76hzLDsLd4o" },
  { id: "BLP-505", cat: "video", title: "Damper Lift",
    maker: "BLP Shop Training", desc: "Setting and checking damper lift timing.",
    formats: ["VIDEO"], youtube: "9xAn4u6RzlA" },
  { id: "BLP-506", cat: "video", title: "Removing an Upright Bass Bridge",
    maker: "BLP Shop Training", desc: "Full removal of an upright bass bridge during belly work.",
    formats: ["VIDEO"], youtube: "D4nldy6U1VM" },
  { id: "BLP-507", cat: "video", title: "How to Chisel a Bridge",
    maker: "BLP Shop Training", desc: "Bridge chiseling technique from the BLP restoration floor.",
    formats: ["VIDEO"], youtube: "E-IICHo9whY" },
  { id: "BLP-508", cat: "video", title: "Choosing Rest Rail Height",
    maker: "BLP Shop Training", desc: "How to choose the correct rest rail height during action work.",
    formats: ["VIDEO"], youtube: "F6QyuY9HaRo" },
  { id: "BLP-509", cat: "video", title: "Grand Regulation: Spring Strength, Drop & Dip",
    maker: "BLP Shop Training", desc: "What to check before starting grand regulation — spring strength, drop, and dip.",
    formats: ["VIDEO"], youtube: "GJgrz7dp3Is" },
  { id: "BLP-510", cat: "video", title: "Arcing Grand Hammers",
    maker: "BLP Shop Training", desc: "Arcing grand hammers for proper string fit.",
    formats: ["VIDEO"], youtube: "hj_bIK1H3hU" },
];

const CATEGORIES = [
  { key: "all",      label: "ALL FILES" },
  { key: "parts",    label: "PARTS" },
  { key: "fixtures", label: "JIGS & FIXTURES" },
  { key: "player",   label: "PLAYER PIANO" },
  { key: "cabinet",  label: "CABINET" },
  { key: "video",    label: "VIDEO" },
];
